# Downloads
dir=/home/swordelf/Downloads
continue=true

# Queue
max-concurrent-downloads=3
max-connection-per-server=4

# RPC
enable-rpc=true
rpc-listen-all=false
rpc-listen-port=6800

# Restore unfinished downloads after restart
input-file=/home/swordelf/.local/state/aria2/session
save-session=/home/swordelf/.local/state/aria2/session
save-session-interval=60

# Unlimited by default
max-overall-download-limit=7500K
max-overall-upload-limit=1M
