monitor = DP-2, 1920x1080@60Hz, 0x0, 1.0

monitor = DP-1, 2560x1440@143.97Hz, 1920x0, 1.3333333
# Nvidia-related env vars.
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

