[[mgr.prepend_keymap]]
on = ["g", "n"]
run = "cd ~/notes"
desc = "Cd to ~/notes"

[[mgr.prepend_keymap]]
on = ["g", "z"]
run = "cd ~/.local/share/chezmoi/"
desc = "Cd to ~/notes"

[[mgr.prepend_keymap]]
on = "z"
run = "plugin fzf-dirs"
desc = "Fuzzy-find directories"

[[mgr.prepend_keymap]]
on = "Z"
run = "plugin fzf"
desc = "Fuzzy-find files"

[[mgr.prepend_keymap]]
on = "<A-i>"
run = "hidden toggle"
desc = "Toggle hidden files"
