wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/wall/wall-main
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/wall/wall-other
    fit_mode = cover
}

ipc = off
