import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8

[font]
normal = { family = "Hasklig" }

[shell]
program = "fish"

[env]
TERM = "xterm-256color"


