theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
# cursorline = true
color-modes = true
completion-timeout = 0
idle-timeout = 0
completion-replace = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false
git-ignore = false
git-exclude = false

[editor.search]
wrap-around = true

[keys.normal]
esc = "collapse_selection"

[keys.normal.space]
w = ":w"
e = ":reload"

[keys.select]
esc = ["normal_mode", "collapse_selection"]

[keys.insert]
"C-." = "code_action"

[editor.lsp]
# display-inlay-hints = true
display-messages = true
goto-reference-include-declaration = false

