theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
# cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false
git-ignore = true
git-exclude = false

[editor.search]
wrap-around = true

[keys.normal.space]
w = ":w"

[editor.lsp]
# display-inlay-hints = true

