theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
# cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[editor.search]
wrap-around = false



